name: C/C++ CI

on:
  push:
    branches: [ "rework-l-option" ]
  pull_request:
    branches: [ "rework-l-option" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # - name: Install valgrind
      # run: sudo apt install valgrind -y

    - name: make test
      run: make test

    - name: make fclean
      run: make fclean
  
